"""Styled HTML report builder."""

from __future__ import annotations

from collections import Counter
from html import escape

from cisco_collab_health.models.assessment import AssessmentReport
from cisco_collab_health.models.findings import FindingSeverity, HealthFinding


class HtmlReportBuilder:
    """Builds a styled standalone HTML report."""

    def build(self, report: AssessmentReport) -> str:
        severity_counts = Counter(finding.severity for finding in report.findings)
        cluster_section = self._cluster_section(report)
        node_rows = self._node_rows(report)
        device_rows = self._device_rows(report)
        collector_issues_section = self._collector_issues_section(report)
        finding_sections = "\n".join(self._finding_section(finding) for finding in report.findings)

        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cisco Collaboration Health Assessment</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f6f7f9;
      --panel: #ffffff;
      --text: #1d2733;
      --muted: #5f6b7a;
      --line: #d9dee7;
      --critical: #b42318;
      --warning: #b54708;
      --info: #175cd3;
    }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Arial, Helvetica, sans-serif;
      line-height: 1.45;
    }}
    header {{
      background: #202a37;
      color: white;
      padding: 28px 32px;
    }}
    header h1 {{
      margin: 0 0 8px;
      font-size: 28px;
    }}
    header p {{
      margin: 0;
      color: #d5dce8;
    }}
    main {{
      max-width: 1120px;
      margin: 0 auto;
      padding: 28px 20px 48px;
    }}
    section {{
      margin: 0 0 24px;
      padding: 22px;
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
    }}
    h2 {{
      margin: 0 0 16px;
      font-size: 20px;
    }}
    h3 {{
      margin: 0 0 10px;
      font-size: 17px;
    }}
    .summary-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 12px;
    }}
    .metric {{
      padding: 14px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fbfcfe;
    }}
    .metric strong {{
      display: block;
      font-size: 24px;
      margin-bottom: 4px;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
    }}
    th, td {{
      padding: 10px 8px;
      border-bottom: 1px solid var(--line);
      text-align: left;
      vertical-align: top;
    }}
    th {{
      color: var(--muted);
      font-size: 13px;
      text-transform: uppercase;
    }}
    .finding {{
      border-left: 5px solid var(--info);
    }}
    .finding.critical {{
      border-left-color: var(--critical);
    }}
    .finding.warning {{
      border-left-color: var(--warning);
    }}
    .finding.info {{
      border-left-color: var(--info);
    }}
    .meta {{
      color: var(--muted);
      font-size: 14px;
      margin-bottom: 12px;
    }}
    .facts {{
      margin: 8px 0 0;
      padding-left: 20px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>Cisco Collaboration Health Assessment</h1>
    <p>Generated by Helios alpha framework</p>
  </header>
  <main>
    <section>
      <h2>Executive Overview</h2>
      <div class="summary-grid">
        <div class="metric"><strong>{len(report.facts.nodes)}</strong><span>Nodes</span></div>
        <div class="metric"><strong>{len(report.facts.devices)}</strong><span>Devices</span></div>
        <div class="metric"><strong>{severity_counts[FindingSeverity.CRITICAL]}</strong>
          <span>Critical</span></div>
        <div class="metric"><strong>{severity_counts[FindingSeverity.WARNING]}</strong>
          <span>Warnings</span></div>
        <div class="metric"><strong>{severity_counts[FindingSeverity.INFO]}</strong>
          <span>Informational</span></div>
      </div>
    </section>
    {cluster_section}
    <section>
      <h2>Discovered Nodes</h2>
      <table>
        <thead><tr><th>Name</th><th>Address</th><th>Role</th><th>Reachable</th></tr></thead>
        <tbody>
          {node_rows}
        </tbody>
      </table>
    </section>
    <section>
      <h2>Device Inventory</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th><th>Model</th><th>Protocol</th>
            <th>Device Pool</th><th>Location</th><th>Load</th>
          </tr>
        </thead>
        <tbody>
          {device_rows}
        </tbody>
      </table>
    </section>
    {collector_issues_section}
    <section>
      <h2>Findings</h2>
      {finding_sections}
    </section>
  </main>
</body>
</html>
"""

    def _cluster_section(self, report: AssessmentReport) -> str:
        if report.facts.cluster is None:
            return """
    <section>
      <h2>Cluster</h2>
      <p>Cluster identity was not collected.</p>
    </section>
"""

        cluster = report.facts.cluster
        return f"""
    <section>
      <h2>Cluster</h2>
      <table>
        <tbody>
          <tr><th>Name</th><td>{escape(cluster.name)}</td></tr>
          <tr><th>Product</th><td>{escape(cluster.product)}</td></tr>
          <tr><th>Version</th><td>{escape(cluster.version)}</td></tr>
        </tbody>
      </table>
    </section>
"""

    def _node_rows(self, report: AssessmentReport) -> str:
        if not report.facts.nodes:
            return '<tr><td colspan="4">No nodes discovered.</td></tr>'

        return "\n".join(
            (
                "<tr>"
                f"<td>{escape(node.name)}</td>"
                f"<td>{escape(node.address)}</td>"
                f"<td>{escape(node.role)}</td>"
                f"<td>{escape(str(node.reachable))}</td>"
                "</tr>"
            )
            for node in report.facts.nodes
        )

    def _device_rows(self, report: AssessmentReport) -> str:
        if not report.facts.devices:
            return '<tr><td colspan="6">No devices inventoried.</td></tr>'

        return "\n".join(
            (
                "<tr>"
                f"<td>{escape(device.name)}</td>"
                f"<td>{escape(device.model or '')}</td>"
                f"<td>{escape(device.protocol or '')}</td>"
                f"<td>{escape(device.device_pool or '')}</td>"
                f"<td>{escape(device.location or '')}</td>"
                f"<td>{escape(device.configured_load or '')}</td>"
                "</tr>"
            )
            for device in report.facts.devices
        )

    def _collector_issues_section(self, report: AssessmentReport) -> str:
        rows = []
        for result in report.collector_results:
            for warning in result.warnings:
                rows.append(
                    "<tr>"
                    f"<td>{escape(result.collector_name)}</td>"
                    "<td>warning</td>"
                    f"<td>{escape(warning)}</td>"
                    "</tr>"
                )
            for error in result.errors:
                rows.append(
                    "<tr>"
                    f"<td>{escape(result.collector_name)}</td>"
                    "<td>error</td>"
                    f"<td>{escape(error.exception_type)}: {escape(error.message)}</td>"
                    "</tr>"
                )
        if not rows:
            return ""

        return f"""
    <section>
      <h2>Collector Issues</h2>
      <table>
        <thead><tr><th>Collector</th><th>Type</th><th>Message</th></tr></thead>
        <tbody>
          {"".join(rows)}
        </tbody>
      </table>
    </section>
"""

    def _finding_section(self, finding: HealthFinding) -> str:
        severity = escape(finding.severity.value)
        facts = "\n".join(f"<li>{escape(fact)}</li>" for fact in finding.facts)
        recommendation = ""
        if finding.recommendation:
            escaped_recommendation = escape(finding.recommendation)
            recommendation = (
                f"<p><strong>Recommendation:</strong> {escaped_recommendation}</p>"
            )
        evidence = self._evidence_list(finding)

        return f"""
      <article class="finding {severity}">
        <h3>{escape(finding.title)}</h3>
        <div class="meta">
          Rule: {escape(finding.rule_id)} |
          Severity: {severity} |
          Type: {escape(finding.recommendation_kind.value)}
        </div>
        <p><strong>Reasoning:</strong> {escape(finding.reasoning)}</p>
        <p><strong>Facts:</strong></p>
        <ul class="facts">
          {facts}
        </ul>
        {evidence}
        {recommendation}
      </article>
"""

    def _evidence_list(self, finding: HealthFinding) -> str:
        if not finding.evidence:
            return ""

        items = []
        for evidence in finding.evidence:
            node = f" | Node: {escape(evidence.node)}" if evidence.node else ""
            artifact = ""
            if evidence.artifact_path:
                artifact = f" | Artifact: {escape(str(evidence.artifact_path))}"
            items.append(
                "<li>"
                f"Source: {escape(evidence.source)} | "
                f"Operation: {escape(evidence.operation)}"
                f"{node}{artifact} | "
                f"Confidence: {escape(evidence.confidence)}"
                "</li>"
            )

        return f"""
        <p><strong>Evidence:</strong></p>
        <ul class="facts">
          {"".join(items)}
        </ul>
"""
